# Latest stable node
FROM node:20.11.1-alpine AS base

ENV NODE_ENV development

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY ./prisma ./prisma
RUN npx prisma generate

CMD ["npm", "run", "dev"]
