version: "3.9"

services:
  personal-website-api:
    image: personal-website-api
    container_name: personal-website-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - MONGO_DB_CONNECTION_STRING=${MONGO_DB_CONNECTION_STRING}
      - API_KEY=${API_KEY}
