version: "3.9"

services:
  redis:
    image: redis:7.2.4-alpine
    networks:
      - default
    ports:
      - 6379:6379

  app:
    image: personal-website-api:dev
    networks:
      - default
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3001:3000
    depends_on:
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - REDIS_URL=${REDIS_URL}
      - REDIS_STORE_SECRET=${REDIS_STORE_SECRET}
      - API_KEY=${API_KEY}

networks:
  default: