version: "3.9"

services:
  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    networks:
      - personalwebsite
    ports:
      - 6379:6379

  personal-website-api:
    image: personal-website-api:dev
    container_name: personal-website-api
    networks:
      - personalwebsite
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3001:3001
    depends_on:
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - REDIS_URL=${REDIS_URL}
      - REDIS_SESSION_SECRET=${REDIS_SESSION_SECRET}
      - API_KEY=${API_KEY}

networks:
  personalwebsite:
    name: personalwebsite
