version: "3.9"

services:
  mongo:
    image: mongo:7.0.6
    container_name: mongo
    networks:
      - personalwebsite
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_data:/data/db

  personal-website-api:
    image: personal-website-api:dev
    container_name: personal-website-api
    networks:
      - personalwebsite
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3001:3001
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - MONGO_DB_CONNECTION_STRING=${MONGO_DB_CONNECTION_STRING}
      - API_KEY=${API_KEY}

networks:
  personalwebsite:
    name: personalwebsite

volumes:
  mongo_data: